// <auto-generated />
using System;
using HeladosMaui.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeladosMaui.Api.Data.Migraciones
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.DetalleOrden", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Agregados")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("HeladoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("OrdenId")
                        .HasColumnType("bigint");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<double>("PrecioTotal")
                        .HasColumnType("float");

                    b.Property<string>("Sabor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("DetalleOrdenes");
                });

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.Helado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Helados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_0.jpg",
                            Nombre = "Vanilla Delight",
                            Precio = 60.25
                        },
                        new
                        {
                            Id = 2,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_1.jpg",
                            Nombre = "ChocoBerry Bliss",
                            Precio = 70.5
                        },
                        new
                        {
                            Id = 3,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_2.jpg",
                            Nombre = "Minty Cookie Crunch",
                            Precio = 8.75
                        },
                        new
                        {
                            Id = 4,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_3.jpg",
                            Nombre = "Strawberry Dream",
                            Precio = 60.950000000000003
                        },
                        new
                        {
                            Id = 5,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_4.jpg",
                            Nombre = "Cookie Dough Extravaganza",
                            Precio = 90.200000000000003
                        },
                        new
                        {
                            Id = 6,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_5.jpg",
                            Nombre = "Caramel Swirl Symphony",
                            Precio = 70.75
                        },
                        new
                        {
                            Id = 7,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_6.jpg",
                            Nombre = "Peanut Butter Paradise",
                            Precio = 80.5
                        },
                        new
                        {
                            Id = 8,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_7.jpg",
                            Nombre = "Mango Tango Tango",
                            Precio = 90.799999999999997
                        },
                        new
                        {
                            Id = 9,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_8.jpg",
                            Nombre = "Hazelnut Heaven",
                            Precio = 80.950000000000003
                        },
                        new
                        {
                            Id = 10,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_9.jpg",
                            Nombre = "Blueberry Bliss Bonanza",
                            Precio = 70.200000000000003
                        },
                        new
                        {
                            Id = 11,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_10.jpg",
                            Nombre = "Toffee Twist Temptation",
                            Precio = 70.950000000000003
                        },
                        new
                        {
                            Id = 12,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_11.jpg",
                            Nombre = "Rocky Road Revelry",
                            Precio = 90.5
                        },
                        new
                        {
                            Id = 13,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_12.jpg",
                            Nombre = "Passionfruit Paradise",
                            Precio = 80.75
                        },
                        new
                        {
                            Id = 14,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_13.jpg",
                            Nombre = "Cotton Candy Carnival",
                            Precio = 70.200000000000003
                        },
                        new
                        {
                            Id = 15,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_14.jpg",
                            Nombre = "Lemon Sorbet Serenity",
                            Precio = 60.899999999999999
                        },
                        new
                        {
                            Id = 16,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_15.jpg",
                            Nombre = "Maple Pecan Pleasure",
                            Precio = 80.25
                        },
                        new
                        {
                            Id = 17,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_16.jpg",
                            Nombre = "Raspberry Ripple Rhapsody",
                            Precio = 70.450000000000003
                        },
                        new
                        {
                            Id = 18,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_17.jpg",
                            Nombre = "Almond Joyful Jubilee",
                            Precio = 90.950000000000003
                        },
                        new
                        {
                            Id = 19,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_18.jpg",
                            Nombre = "Blue Lagoon Bliss",
                            Precio = 80.5
                        },
                        new
                        {
                            Id = 20,
                            Imagen = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/main/Icecreams/small/ic_19.jpg",
                            Nombre = "Coconut Caramel Carnival",
                            Precio = 70.799999999999997
                        });
                });

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.OpcionesDeHelado", b =>
                {
                    b.Property<int>("HeladoId")
                        .HasColumnType("int");

                    b.Property<string>("Sabor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Agregados")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HeladoId", "Sabor", "Agregados");

                    b.ToTable("OpcionesDeHelados");

                    b.HasData(
                        new
                        {
                            HeladoId = 1,
                            Sabor = "Vanilla",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 1,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 1,
                            Sabor = "Default",
                            Agregados = "Whipped Cream"
                        },
                        new
                        {
                            HeladoId = 2,
                            Sabor = "Chocolate",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 2,
                            Sabor = "Strawberry",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 2,
                            Sabor = "Default",
                            Agregados = "Sprinkles"
                        },
                        new
                        {
                            HeladoId = 3,
                            Sabor = "Mint Chocolate Chip",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 3,
                            Sabor = "Default",
                            Agregados = "Cherries"
                        },
                        new
                        {
                            HeladoId = 3,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 4,
                            Sabor = "Strawberry",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 4,
                            Sabor = "Default",
                            Agregados = "Sprinkles"
                        },
                        new
                        {
                            HeladoId = 4,
                            Sabor = "Default",
                            Agregados = "Whipped Cream"
                        },
                        new
                        {
                            HeladoId = 5,
                            Sabor = "Cookie Dough",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 5,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 5,
                            Sabor = "Default",
                            Agregados = "Cherries"
                        },
                        new
                        {
                            HeladoId = 6,
                            Sabor = "Vanilla",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 6,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 6,
                            Sabor = "Default",
                            Agregados = "Cherries"
                        },
                        new
                        {
                            HeladoId = 7,
                            Sabor = "Chocolate",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 7,
                            Sabor = "Default",
                            Agregados = "Whipped Cream"
                        },
                        new
                        {
                            HeladoId = 7,
                            Sabor = "Default",
                            Agregados = "Sprinkles"
                        },
                        new
                        {
                            HeladoId = 8,
                            Sabor = "Strawberry",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 8,
                            Sabor = "Cookie Dough",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 8,
                            Sabor = "Default",
                            Agregados = "Sprinkles"
                        },
                        new
                        {
                            HeladoId = 9,
                            Sabor = "Mint Chocolate Chip",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 9,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 9,
                            Sabor = "Default",
                            Agregados = "Whipped Cream"
                        },
                        new
                        {
                            HeladoId = 10,
                            Sabor = "Chocolate",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 10,
                            Sabor = "Strawberry",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 10,
                            Sabor = "Default",
                            Agregados = "Cherries"
                        },
                        new
                        {
                            HeladoId = 11,
                            Sabor = "Vanilla",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 11,
                            Sabor = "Default",
                            Agregados = "Whipped Cream"
                        },
                        new
                        {
                            HeladoId = 11,
                            Sabor = "Default",
                            Agregados = "Cherries"
                        },
                        new
                        {
                            HeladoId = 12,
                            Sabor = "Chocolate",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 12,
                            Sabor = "Mint Chocolate Chip",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 12,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 13,
                            Sabor = "Strawberry",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 13,
                            Sabor = "Default",
                            Agregados = "Sprinkles"
                        },
                        new
                        {
                            HeladoId = 13,
                            Sabor = "Default",
                            Agregados = "Whipped Cream"
                        },
                        new
                        {
                            HeladoId = 14,
                            Sabor = "Cookie Dough",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 14,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 14,
                            Sabor = "Default",
                            Agregados = "Cherries"
                        },
                        new
                        {
                            HeladoId = 15,
                            Sabor = "Vanilla",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 15,
                            Sabor = "Strawberry",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 15,
                            Sabor = "Default",
                            Agregados = "Sprinkles"
                        },
                        new
                        {
                            HeladoId = 16,
                            Sabor = "Chocolate",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 16,
                            Sabor = "Mint Chocolate Chip",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 16,
                            Sabor = "Default",
                            Agregados = "Whipped Cream"
                        },
                        new
                        {
                            HeladoId = 17,
                            Sabor = "Strawberry",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 17,
                            Sabor = "Cookie Dough",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 17,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 18,
                            Sabor = "Vanilla",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 18,
                            Sabor = "Default",
                            Agregados = "Sprinkles"
                        },
                        new
                        {
                            HeladoId = 18,
                            Sabor = "Default",
                            Agregados = "Cherries"
                        },
                        new
                        {
                            HeladoId = 19,
                            Sabor = "Chocolate",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 19,
                            Sabor = "Strawberry",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 19,
                            Sabor = "Default",
                            Agregados = "Whipped Cream"
                        },
                        new
                        {
                            HeladoId = 20,
                            Sabor = "Mint Chocolate Chip",
                            Agregados = "Default"
                        },
                        new
                        {
                            HeladoId = 20,
                            Sabor = "Default",
                            Agregados = "Chocolate Sauce"
                        },
                        new
                        {
                            HeladoId = 20,
                            Sabor = "Default",
                            Agregados = "Sprinkles"
                        });
                });

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.Orden", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClienteDireccion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("OrdenFecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("PrecioTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("ContraseñaSalt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.DetalleOrden", b =>
                {
                    b.HasOne("HeladosMaui.Api.Data.Entidades.Orden", "Orden")
                        .WithMany("DetalleOrdenes")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.OpcionesDeHelado", b =>
                {
                    b.HasOne("HeladosMaui.Api.Data.Entidades.Helado", "Helado")
                        .WithMany("OpcionesDeHelados")
                        .HasForeignKey("HeladoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Helado");
                });

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.Helado", b =>
                {
                    b.Navigation("OpcionesDeHelados");
                });

            modelBuilder.Entity("HeladosMaui.Api.Data.Entidades.Orden", b =>
                {
                    b.Navigation("DetalleOrdenes");
                });
#pragma warning restore 612, 618
        }
    }
}
